language: python
dist: xenial
cache:
- pip
python:
- 3.5
- 3.6
- 3.7
install:
- pip install -U tox-travis
before_install:
- sudo apt-get install pandoc
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: tbuli
  password:
    secure: Zad+9f58hGj8+4opgxRrU6BYTaN79XnDzz4AU6TNrlNn6Onx9rXt+3KtOIIWAu3XUUGx/MNjJLN7YhKr5tAbjDNSL7zkJxhQFp01OwhgSAWo1iXWzf4gy+FExNRGG9HV8tx5ImJhl2uhsiNGNCUCuFg6IaWQcufYhPXiIgrG0PTqVZDvJdBvpXLW6kxkU/euRRDYOBU8jacdNmEPkyySzKoZoGKESqrS6l4wnFcjUxqmCC8qlQPXRXrroK8nsnKCaMaGf4Tb5J9SvPg8bcAVhMOEpwOzYdibk8fxf+hlabU7UMHbwL3Q95sksIzVct7ORwK+36w2fE9vkBipElu9jQp1Q2aeYSkvSmkY+Yobj1zgg3b9t9TFsZhwwSmYCmwsfnEzKONyNaeiVrEL9T2e04C9tR/aMKs0r+NcJkU5icFhX9RwJgfSMW3i013vTWgL2BCSIhWUxb7C13LEmW5xKZpPs87sV5y7EUPKciToa24a47KBgCLA03/SKCbGCHkDL9GtvJQRGtT1PqcOBaTT0V9r6oUrUfZ4C84D2Q15VjpxBfZjhO375Il/8Rr025RRG1EoJq0azHNRTUJcoo8SM6mo9A4NFg+cM5NsQBRNXWSs/MkGNgsgFsDkIjoSEQqSEKQFNG7KHZIM8VU0q8CJXoIS/5vxiFxQPJ4Vg8rEDOA=
  on:
    tags: true
    repo: tBuLi/Deconvoluted
    python: 3.6
jobs:
  fast_finish: true
  include:
  - stage: docs
    python: '3.7'
    before_install:
    - sudo apt-get install pandoc
    install:
    - pip install --upgrade -r requirements_docs.txt
    - pip install --upgrade .[all]
    script:
    - mkdir docs_build
    - sphinx-build -nW -b html docs docs_build
